image: "gitpod/workspace"

tasks:
  - name: "Install dependencies"
    before: |
      curl -L https://foundry.paradigm.xyz | bash
      source ~/.bashrc
    init: "foundryup"

vscode:
  extensions:
    - "esbenp.prettier-vscode"
    - "NomicFoundation.hardhat-solidity"
